### ISSUE TITLE
Wrong Delta character

### ISSUE THREAD

**Issue by jmd-dk** [a-ludi/sublime-greek-letters#1]
The Delta character used is `∆` (INCREMENT), whereas it should be `Δ` (GREEK CAPITAL LETTER DELTA).

One quick way of checking the full Unicode name of a character literal is
`python3 -c "import unicodedata; print(unicodedata.name('∆'))"`

**Comment by a-ludi** [comment]
Thanks for noting. I fixed it and the [new version 1.0.1](https://github.com/a-ludi/sublime-greek-letters/releases/tag/v1.0.1) will be available soon.
